- hosts: webservers
  any_errors_fatal: true
  vars:
    deploy_user: deploy
    ## Required vars that should be passed using `--extra-vars` when calling ansible-playbook:
    #git_deploy_repo: git@github.com:tag1consulting/tag1consulting.com.git
    #git_tag: dev
  become: "{{ deploy_user }}"
  tasks:
    - name: "Ensure releases directory exists"
      file:
        path: "/var/www/{{ site }}/releases"
        owner: "{{ deploy_user }}"
        group: "{{ deploy_user }}"
        mode: 0755
        state: directory
      become: root

    - name: "Clone branch/tag"
      git:
        repo: "{{ git_deploy_repo }}"
        dest: "/var/www/{{ site }}/releases/{{ git_tag }}"
        version: "{{ git_tag }}"

    - name: "Check for .env"
      stat:
        path: /var/www/{{ site }}/settings/environment
      register: use_env

    - name: "Check for settings.local.php"
      stat:
        path: /var/www/{{ site }}/settings/settings.local.php
      register: use_settings_local

    - name: "Check for services.yml"
      stat:
        path: /var/www/{{ site }}/settings/services.yml
      register: use_services_yml

    - name: "Symlinking environment settings file"
      file:
        src: /var/www/{{ site }}/settings/environment
        dest: /var/www/{{ site }}/releases/{{ git_tag }}/.env
        state: link
      when: use_env

    - name: "Symlinking settings.local.php"
      file:
        src: /var/www/{{ site }}/settings/settings.local.php
        dest: /var/www/{{ site }}/releases/{{ git_tag }}/sites/default/settings.local.php
        state: link
      when: use_settings_local

    - name: "Symlink services.yml"
      file:
        src: /var/www/{{ site }}/settings/services.yml
        dest: /var/www/{{ site }}/releases/{{ git_tag }}/sites/default/services.yml
        state: link
      when: use_services_yml

    - name: "Set up persistent storage"
      file:
        path: "{{ drupal_files_source }}"
        owner: www-data
        group: www-data
        state: directory
        recurse: true

    - name: "Symlink persistent storage"
      file:
        src: "{{ drupal_files_source }}"
        dest: /var/www/{{ site }}/releases/{{ git_tag }}/sites/default/files
        state: link

    - name: "Making {{ git_tag }} live"
      file:
        src: /var/www/{{ site }}/releases/{{ git_tag }}
        dest: /var/www/{{ site }}/current
        state: link
        force: true
